Repository innovationacademy-kr/slabs-saver, pull requests merged in 2021-05, with the labels that each got.

#14 Signup and login
  .gitignore
  slap-saver/.env.sample
  slap-saver/app.js
  slap-saver/controllers/authorController.js
  slap-saver/lib/authorPassport.js
  slap-saver/migrations/20210510100353-create-author.js
  slap-saver/models/author.js
  slap-saver/models/validator/authorValidator.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/public/javascripts/authorSignup.js
  slap-saver/routes/author.js
  slap-saver/views/author/login.ejs
  slap-saver/views/author/signup.ejs
Labels: enhancement

#17 Author dev
  slap-saver/controllers/authorController.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/public/javascripts/addSection.js
  slap-saver/routes/author.js
  slap-saver/views/author/articles.ejs
  slap-saver/views/author/checkArticle.ejs
  slap-saver/views/author/editArticle.ejs
  slap-saver/views/author/editMeeting.ejs
  slap-saver/views/author/index.ejs
  slap-saver/views/author/newArticle.ejs
Labels: enhancement

#22 Associate model
  slap-saver/controllers/authorController.js
  slap-saver/lib/authorPassport.js
  slap-saver/migrations/20210510100353-create-author.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/models/author.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/routes/author.js
  slap-saver/seeders/20210513063808-authors.js
  slap-saver/seeders/20210514003753-articles.js
  slap-saver/views/author/articles.ejs
Labels: enhancement

#25 User dev
  slap-saver/controllers/articleController.js
  slap-saver/controllers/userController.js
  slap-saver/public/javascripts/detail.js
  slap-saver/routes/articles.js
  slap-saver/routes/index.js
  slap-saver/seeders/20210514003753-articles.js
  slap-saver/views/articles/article.ejs
  slap-saver/views/index.ejs
  slap-saver/views/partials/articleCard.ejs
Labels: enhancement

#29 Desk
  slap-saver/controllers/authorController.js
  slap-saver/controllers/userController.js
  slap-saver/lib/constants/category.js
  slap-saver/lib/convertCategory.js
  slap-saver/migrations/20210510100353-create-author.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/models/author.js
  slap-saver/models/validator/authorValidator.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/public/stylesheets/authorIndex.css
  slap-saver/seeders/20210513063808-authors.js
  slap-saver/seeders/20210514003753-articles.js
  slap-saver/views/author/editArticle.ejs
  slap-saver/views/author/index.ejs
  slap-saver/views/author/newArticle.ejs
  slap-saver/views/author/signup.ejs
Labels: enhancement

#35 Mobile view dev
  slap-saver/controllers/articleController.js
  slap-saver/controllers/userController.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/public/javascripts/detail.js
  slap-saver/public/stylesheets/style.css
  slap-saver/seeders/20210513063808-authors.js
  slap-saver/seeders/20210514003753-articles.js
  slap-saver/views/articles/article.ejs
  slap-saver/views/index.ejs
  slap-saver/views/partials/articleCard.ejs
Labels: enhancement

#36 Desk feat
  slap-saver/controllers/authorController.js
  slap-saver/lib/constants/category.js
  slap-saver/lib/getCurrentUser.js
  slap-saver/lib/isEmptyObject.js
  slap-saver/models/article.js
  slap-saver/public/javascripts/author/index.js
  slap-saver/routes/author.js
  slap-saver/seeders/20210514003753-articles.js
  slap-saver/views/author/index.ejs
Labels: enhancement

#47 Author article refactor
  slap-saver/controllers/authorController.js
  slap-saver/lib/constants/articleStatus.js
  slap-saver/lib/constants/category.js
  slap-saver/lib/getRandomInt.js
  slap-saver/migrations/20210510100353-create-author.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/models/author.js
  slap-saver/models/validator/authorValidator.js
  slap-saver/seeders/20210513063808-authors.js
  slap-saver/seeders/20210518015026-chief.js
  slap-saver/seeders/20210518015820-desks.js
  slap-saver/seeders/20210518020750-authors.js
  slap-saver/seeders/20210518020946-articles.js
  slap-saver/views/author/articles.ejs
  slap-saver/views/author/desking/chiefEditor.ejs
  slap-saver/views/author/desking/desk.ejs
  slap-saver/views/author/desking/index.ejs
  slap-saver/views/author/editArticle.ejs
  slap-saver/views/author/login.ejs
  slap-saver/views/author/newArticle.ejs
  slap-saver/views/index.ejs
Labels: enhancement, refacoring

#54 Paragraph refactor
  slap-saver/controllers/articleController.js
  slap-saver/controllers/authorController.js
  slap-saver/controllers/userController.js
  slap-saver/migrations/20210511094505-create-articles.js
  slap-saver/models/article.js
  slap-saver/public/javascripts/addSection.js
  slap-saver/seeders/20210518020946-articles.js
  slap-saver/views/articles/article.ejs
  slap-saver/views/author/articles.ejs
  slap-saver/views/author/checkArticle.ejs
  slap-saver/views/author/desking/chiefEditor.ejs
  slap-saver/views/author/desking/desk.ejs
  slap-saver/views/author/desking/index.ejs
  slap-saver/views/author/editArticle.ejs
  slap-saver/views/author/newArticle.ejs
Labels: enhancement, refacoring

#58 Mailing dev
  slap-saver/controllers/authorController.js
  slap-saver/controllers/userController.js
  slap-saver/lib/convertCategory.js
  slap-saver/lib/converter.js
  slap-saver/lib/getCurrentUser.js
  slap-saver/lib/sendMail.js
  slap-saver/migrations/20210517095942-create-invitation.js
  slap-saver/models/invitation.js
  slap-saver/package-lock.json
  slap-saver/package.json
  slap-saver/public/javascripts/detail.js
  slap-saver/public/javascripts/modal.js
  slap-saver/public/stylesheets/style.css
  slap-saver/routes/author.js
  slap-saver/seeders/20210517114958-invitations.js
  slap-saver/seeders/20210518015820-desks.js
  slap-saver/seeders/20210518094141-admin.js
  slap-saver/views/admin/index.ejs
  slap-saver/views/admin/invitation.ejs
  slap-saver/views/articles/article.ejs
  slap-saver/views/author/desking/desk.ejs
  slap-saver/views/author/preSignup.ejs
  slap-saver/views/author/signup.ejs
Labels: enhancement

#87 Current user on navbar
  slap-saver/controllers/authorController.js
  slap-saver/models/article.js
  slap-saver/public/javascripts/addSection.js
  slap-saver/public/stylesheets/author/common.css
  slap-saver/seeders/20210518015026-chief.js
  slap-saver/seeders/20210518015820-desks.js
  slap-saver/seeders/20210518020750-authors.js
  slap-saver/seeders/20210518020946-articles.js
  slap-saver/views/author/editArticle.ejs
  slap-saver/views/author/newArticle.ejs
  slap-saver/views/partials/navbar.ejs
Labels: bug, enhancement

#91 Fix user detail
  slap-saver/controllers/articleController.js
  slap-saver/controllers/userController.js
  slap-saver/lib/sendMail.js
  slap-saver/public/javascripts/detail.js
  slap-saver/public/stylesheets/style.css
  slap-saver/views/articles/article.ejs
  slap-saver/views/index.ejs
  slap-saver/views/partials/articleCard.ejs
Labels: enhancement

#90 fix: 여러 버그 수정
  slap-saver/controllers/articleController.js
  slap-saver/controllers/authorController.js
  slap-saver/routes/author.js
  slap-saver/views/author/desking/chiefEditor.ejs
  slap-saver/views/author/desking/desk.ejs
  slap-saver/views/author/desking/index.ejs
  slap-saver/views/author/editArticle.ejs
Labels: bug

#100 fix: #99 ejs layout title 에러 해결
  slap-saver/controllers/articleController.js
  slap-saver/controllers/userController.js
  slap-saver/models/article.js
  slap-saver/public/javascripts/infiniteScroll.js
  slap-saver/views/layout/layout.ejs
Labels: bug
