Repository innovationacademy-kr/slabs-saver, pull requests merged in 2021-08, with the labels that each got.

#310 hotfix: #309 북마크 모델 연관관계 설정 버그 수정
  saver-web/controllers/bookmark/bookmarkController.js
  saver-web/models/bookmark.js
  saver-web/models/subscriber.js
Labels: bug

#303 feat : 안드로이드에서 페이스북 공유시 페이스북 앱이 열리도록 설정
  saver-android/app/build.gradle
  saver-android/app/src/main/AndroidManifest.xml
  saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt
  saver-android/app/src/main/java/com/seoul42/saver_android/MyWebClient.kt
  saver-android/app/src/main/res/layout/activity_main.xml
  saver-android/app/src/main/res/values/themes.xml
Labels: enhancement

#312 feat : #311 북마크 버튼 기능 추가
  saver-web/app.js
  saver-web/controllers/bookmark/bookmarkController.js
  saver-web/middlewares/auth.js
  saver-web/public/javascripts/bookmark.js
  saver-web/public/javascripts/infiniteScroll.js
  saver-web/public/javascripts/user/article.js
  saver-web/routes/bookmark.js
  saver-web/routes/subscriber.js
  saver-web/views/layout/userLayout.ejs
Labels: enhancement

#315 feat: #314 북마크 정보 가져오기/무한 스크롤 구현
  saver-web/controllers/bookmark/bookmarkController.js
  saver-web/public/javascripts/bookmarkInfiniteScroll.js
  saver-web/routes/bookmark.js
  saver-web/views/user/bookmark.ejs
Labels: enhancement

#329 feat : #327 북마크 밀어서 삭제
  saver-web/controllers/bookmark/bookmarkController.js
  saver-web/public/javascripts/bookmark.js
  saver-web/public/javascripts/bookmarkInfiniteScroll.js
  saver-web/views/user/bookmark.ejs
Labels: enhancement

#336 refactor: 안드로이드 필요없는 부분 삭제
  saver-android/app/src/main/AndroidManifest.xml
  saver-android/app/src/main/res/values/strings.xml
Labels: refacoring

#334 feat: 푸시 알림을 보내는 페이지 구현
  saver-web/app.js
  saver-web/controllers/firebase/firebaseController.js
  saver-web/public/javascripts/sendPush.js
  saver-web/public/stylesheets/author/index.css
  saver-web/routes/author.js
  saver-web/routes/firebase.js
  saver-web/views/author/pushPage.ejs
  saver-web/views/author/pushSendPage.ejs
  saver-web/views/layout/adminLayout.ejs
  saver-web/views/partials/navbar.ejs
Labels: enhancement

#350 feat : author/push 페이지 제작
  saver-web/app.js
  saver-web/controllers/firebase/firebaseController.js
  saver-web/public/javascripts/author/sendPush.js
  saver-web/public/stylesheets/author/index.css
  saver-web/routes/author.js
  saver-web/routes/firebase.js
  saver-web/views/author/pushPage.ejs
  saver-web/views/author/pushSendPage.ejs
  saver-web/views/partials/navbar.ejs
Labels: enhancement

#357 feat: #326 안드로이드 앱에 JavascriptInterface 인터페이스 추가
  saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt
  saver-android/app/src/main/java/com/seoul42/saver_android/MyWebClient.kt
  saver-android/app/src/main/java/com/seoul42/saver_android/WebAppInterface.kt
Labels: enhancement

#360 refactor: #359 팔로잉 순서 변경
  saver-web/controllers/user/sectionController.js
  saver-web/lib/constants/category.js
  saver-web/lib/converter.js
  saver-web/public/javascripts/sectionCategory.js
  saver-web/public/javascripts/sectionFollowButton.js
  saver-web/views/user/loginedSection.ejs
Labels: refacoring

#365 feat: #364 팔로우/로그인시 안드로이드 구독하기
  saver-web/controllers/subscriber/subscriberController.js
  saver-web/public/javascripts/sectionFollowButton.js
  saver-web/views/subscriber/login.ejs
Labels: enhancement

#381 fix: 안드로이드 userAgent 설정 추가
  saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt
Labels: bug

#377 feat: #375 관리자 페이지 전체 페이지네이션
  saver-web/controllers/author/article/articleController.js
  saver-web/controllers/author/authorController.js
  saver-web/controllers/author/today/todayController.js
  saver-web/views/author/articles.ejs
  saver-web/views/author/desking/chiefEditor.ejs
  saver-web/views/author/desking/desk.ejs
  saver-web/views/author/desking/index.ejs
  saver-web/views/author/today/todaywordDesking.ejs
  saver-web/views/author/todayArticle/todayArticleDesking.ejs
Labels: enhancement

#385 fix : #383 북마크 css 수정
  saver-web/public/javascripts/bookmarkInfiniteScroll.js
Labels: bug

#388 fix : 안드로이드 카카오톡 쉐어 버그
  saver-android/app/src/main/java/com/seoul42/saver_android/MyWebClient.kt
Labels: bug

#398 feat: #395 favicon 추가
  saver-web/public/stylesheets/icons/favicon.ico
  saver-web/views/layout/adminLayout.ejs
  saver-web/views/layout/layout.ejs
  saver-web/views/layout/userLayout.ejs
Labels: enhancement

#414 Feature/schedule ampm7
  saver-web/app.js
  saver-web/controllers/today/ampmController.js
  saver-web/controllers/user/userController.js
  saver-web/lib/constants/category.js
  saver-web/lib/converter.js
  saver-web/lib/scheduler.js
  saver-web/package.json
  saver-web/public/javascripts/infiniteScroll.js
  saver-web/public/javascripts/user/index.js
  saver-web/public/stylesheets/user/common.css
  saver-web/routes/today.js
Labels: enhancement

#431 fix: #430 안드로이드 구독 수정
  saver-web/public/javascripts/sectionFollowButton.js
  saver-web/public/javascripts/user/index.js
  saver-web/views/subscriber/login.ejs
Labels: bug

#432 feat: #245 이전 기사 링크 추가 기능 구현
  saver-web/controllers/author/article/articleController.js
  saver-web/public/javascripts/author/newArticle.js
  saver-web/public/javascripts/author/searchBox.js
  saver-web/public/stylesheets/author/common.css
  saver-web/routes/author.js
  saver-web/views/author/editArticle.ejs
  saver-web/views/author/newArticle.ejs
Labels: enhancement

#453 fix: 디테일 페이지 카카오 공유 버그 해결
  saver-web/views/user/article.ejs
Labels: bug

#454 fix: #451 섹션 안내문구 수정
  saver-web/public/javascripts/sectionCategory.js
  saver-web/public/stylesheets/user/pages/section.css
Labels: enhancement

#455 fix: 로그인 안된 상태의 페이지 수정
  saver-web/controllers/user/sectionController.js
  saver-web/public/stylesheets/user/pages/section.css
  saver-web/views/user/section.ejs
Labels: bug

#456 fix: 화이트 박스 크기 조정 & footer에 가려지는 문제 수정
  saver-web/public/stylesheets/user/pages/section.css
  saver-web/views/user/loginedSection.ejs
  saver-web/views/user/section.ejs
Labels: bug

#458 fix: #450 업데이트 버튼 위치 이동
  saver-web/public/stylesheets/author/common.css
  saver-web/public/stylesheets/author/index.css
  saver-web/views/author/desking/chiefEditor.ejs
  saver-web/views/author/desking/desk.ejs
  saver-web/views/author/today/todaywordDesking.ejs
  saver-web/views/author/todayArticle/todayArticleDesking.ejs
Labels: bug

#460 fix: chief 페이지 수정버튼 위치 조절
  saver-web/public/stylesheets/author/common.css
  saver-web/views/author/desking/chiefEditor.ejs
Labels: bug

#462 fix: 버튼 디자인 수정
  saver-web/public/stylesheets/author/index.css
  saver-web/views/author/articles.ejs
  saver-web/views/author/desking/chiefEditor.ejs
  saver-web/views/author/desking/desk.ejs
  saver-web/views/author/desking/index.ejs
  saver-web/views/author/pushPage.ejs
  saver-web/views/author/today/todaywordDesking.ejs
  saver-web/views/author/todayArticle/todayArticleDesking.ejs
Labels: bug

#465 fix: 업데이트 버튼 먹통 오류 해결
  saver-web/public/javascripts/author/index.js
  saver-web/views/author/desking/desk.ejs
  saver-web/views/author/today/todaywordDesking.ejs
  saver-web/views/author/todayArticle/todayArticleDesking.ejs
Labels: bug

#467 fix: #464 섹션메뉴 선택시 버튼 색상 미변경 버그 수정
  saver-web/views/user/components/foo.ejs
Labels: bug

#474 fix: 전체 페이지 수 오류
  saver-web/controllers/author/today/todayController.js
  saver-web/controllers/firebase/firebaseController.js
Labels: bug

#478 fix: #469 < 버튼을 눌렀을때 메인페이지로 이동하면서 구독이 다시되는 현상 수정
  saver-web/public/javascripts/user/index.js
Labels: bug

#479 fix: 이전 기사 prefix 변경
  saver-web/public/javascripts/author/searchBox.js
Labels: enhancement

#482 feat: 관리자 기사 검색 업그레이드
  saver-web/controllers/author/article/articleController.js
Labels: enhancement

#500 feat: 토큰이 유효하지 않을 경우 로그인페이지로 리다이렉트
  saver-web/public/javascripts/alarmStatus.js
Labels: enhancement

#531 feat: contact 페이지 구현
  saver-web/.env.sample
  saver-web/controllers/user/settingController.js
  saver-web/lib/sendContactMail.js
  saver-web/public/javascripts/buildSetting.js
  saver-web/public/stylesheets/user/pages/bookmark_alarm.css
  saver-web/routes/setting.js
  saver-web/views/user/contact.ejs
  saver-web/views/user/setting.ejs
Labels: enhancement
